---
title: "APOENA DADOS"
subtitle: "Informações sobre a Lei Aldir Blanc"
author: "[APOENA](https://apoenaredecultural.wordpress.com/)"
date: "12 de setembro de 2021: <br><br>   última atualização: <br> `r format(Sys.Date(), '%d de %B de %Y')`"
output: 
  cleanrmd::html_document_clean:
    theme: new
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```

## O que é o APOENA

O Projeto APOENA - Rede de Diagnóstico e Avaliação de Políticas e Ações Culturais - foco RJ é uma de rede multidisciplinar e multi-institucional destinada ao estudo de ações culturais em seus diferentes níveis; sejam eles, sociais, econômicos, políticos, institucionais, normativos ou formacionais.  O nome APOENA vem do tupi-guarani, e significa "aquele que enxerga longe".

[Clique aqui e saiba mais](https://apoenaredecultural.wordpress.com/)





# Linha do Tempo

- [Linha do Tempo](https://apoena-uff.github.io/dados/linha-tempo/)


# Mapas

#### Fonte: CNM

Mapa do valor total repassado
- [Brasil por UF](mapa_cnm_uf/mapa_01.html)


#### Fonte: EPCult

Mapa do percentual de execução da Lei Aldir Blanc no estado do Rio de Janeiro.    
Legenda:    
  Amarelo: execução abaixo da média    
  Laranja: execução acima da média    
  Cinza: informação não disponível    

- [RJ por município](mapa1/mapa_01.html)

Mapa do percentual de execução da Lei Aldir Blanc por região 

(versão preliminar - verificar a mudança do CEPERJ)

- [RJ por região](mapa2/mapa_reg_01.html)

# Gráficos

- [em breve](https://labacuff.wordpress.com/)

## Outros links

- [APOENA](https://apoenaredecultural.wordpress.com/)

- [LABAC UFF](https://labacuff.wordpress.com/)

