---
title: "LAB"
output: 
  flexdashboard::flex_dashboard:
    theme:
       bootswatch: journal
       bg: "#c2d5db"
       fg: "#1e698d"
       primary: "#1e698d"
       heading_font: 
         google: Sen
       base_font:
         google: Sen
       code_font:
         google: JetBrains Mono
    orientation: rows
    vertical_layout: fill
    navbar:
      - { title: "APOENA", href: "https://apoenaredecultural.wordpress.com/", align: right, icon: glyphicon-time}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE, warning = FALSE,comment = NA)
library(flexdashboard)
#8abca7 verde
#131925 preto
#c2d5db branco
# Row {data-width=100}
library(dplyr)
library(ggplot2)
library(plotly)
library(waffle)
library(janitor)
library(readxl)
BD_APOENA <- read_excel("base_de_dados/dados_para_mapa/Clarissa/base de dados APOENA 18-09-2021.xlsx", 
                        sheet = "base geral (steven) ") %>% clean_names()

dic_dados_LAB <- read_excel("base_de_dados/dados_para_mapa/Clarissa/base de dados APOENA 18-09-2021.xlsx", 
                            sheet = "notas tecnicas") %>% clean_names()

```

Informações básicas
=============================================


Value Boxes {data-width=200}
-------------------------------------

### Valor total

```{r}
#

valueBox(format(sum(BD_APOENA$valor_total,na.rm = T),big.mark='.',
 small.mark=',',decimal.mark=','), caption = "Valor total", color = "info", icon = "fa-twitter")

```

### Pagamentos realizados pela união

```{r}
valueBox(format(sum(BD_APOENA$pagamentos_realizados_pela_uniao,na.rm = T),big.mark='.',
 small.mark=',',decimal.mark=','), caption = "Pagamento realizados pela união", icon = "fa-github")
```

### Percentual de plano aprovado e pagamento

```{r}
#situacao_do_plano_e_pagamento
valueBox(format(74.98,big.mark='.',
 small.mark=',',decimal.mark=','), caption = "Percentual de plano aprovado e pagamento", color = "lightgray", icon = "glyphicon-time")
```

### Saldo em conta plataforma de indicadores

```{r}
valueBox(format(sum(BD_APOENA$saldo_em_conta_plataforma_de_indicadores,na.rm = T),big.mark='.',
 small.mark=',',decimal.mark=','), caption = "Saldo em conta plataforma de indicadores", color = "warning", icon = "fa-facebook")
```

### planos aprovados em 2020

```{r}
valueBox(format(4175,big.mark='.',
 small.mark=',',decimal.mark=','), caption = "planos aprovados em 2020", color = "danger", icon = "fa-facebook")
```

### planos aprovados em 2021

```{r}

valueBox(format(538,big.mark='.',
 small.mark=',',decimal.mark=','), caption = "planos aprovados em 2021", color = "lightgray",
  icon = "fab fa-r-project"
)
```

Row 
---------------------------------------------

### Scatter Chart with geom_point

```{r}
#p <- ggplot(BD_APOENA) +
#   aes(x = plano_aprovado_2021, colour = plano_aprovado_2021,fill=plano_aprovado_2021) +
#   geom_bar() +
#   scale_color_hue() +
#   theme_minimal()
#ggplotly(p)
```

Row 
---------------------------------------------


### Chart B

```{r}

```

### Chart C

```{r}

```


Dicionário de dados
=======================================================================


Dicionário de dados, Fonte dos dados e algumas notas técnicas